---
- hosts: nextcloud
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: configure updater.server.url
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: /home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php
      regexp: "^.*'updater.server.url' =>.*,$"
      line: "  'updater.server.url' => '{{updater_server_url}}',"
      insertbefore: '^\)\;'
    when: updater_server_url is defined

  - name: Update Nextcloud with backup
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      php updater.phar --no-interaction || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud/updater"
    when: update_with_backup == True

  - name: Update Nextcloud without backup
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      php updater.phar --no-interaction --no-backup || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud/updater"
    when: update_with_backup == False

  - name: Upgrade Nextcloud
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      php occ upgrade --no-interaction || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"

  - name: Database Optimisations
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      php occ db:add-missing-primary-keys --no-interaction || exit -1
      php occ db:add-missing-columns --no-interaction || exit -1
      php occ db:add-missing-indices --no-interaction | exit -1
      php occ db:convert-filecache-bigint --no-interaction || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"

  - name: Update all apps
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      php occ app:update --all -n --no-ansi || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
