---
- hosts: nextcloud
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  #################################
  ## remove the domain, the database, the user
  #################################
  - name: drop domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="false"
  - name: drop database
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="{{dbms}}" exists="false"
  - name: remove user
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="false"
