---
- hosts: nextcloud
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp
    random_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"

  tasks:
  - name: Create user, domain and database
    import_tasks: tasks/hs_basis.yml

  #################################
  ## create directories
  #################################
  - name: create directory nextcloud
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      state: directory
  - name: create directory etc
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/etc"
      state: directory
  - name: create directory var/tmp
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/tmp"
      state: directory
  - name: create directory var/log
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/log"
      state: directory
  - name: create directory var/run
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/run"
      state: directory


  #################################
  ## setup the data directory
  #################################
  - name: Check for HDD storage
    stat:
      path: /home/storage/{{pac}}/users/{{user}}
    register: hdd_storage
  - name: create data directory on storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/storage/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: hdd_storage.stat.exists

  - name: create symbolic link for data to storage
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/storage/{{pac}}/users/{{user}}/data"
      dest: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: link
    when: hdd_storage.stat.exists

  - name: create data directory on sdd
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/data"
      state: directory
      mode: 0744
    when: not hdd_storage.stat.exists

  ##################################
  ## install nextcloud
  ##################################
  - name: install nextcloud
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      src: https://download.nextcloud.com/server/releases/nextcloud-{{nextcloud_version}}.tar.bz2
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/nextcloud
      extra_opts: [--strip-components=1]

  - name: finish nextcloud installation
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      # see https://docs.nextcloud.com/server/latest/admin_manual/installation/command_line_installation.html
      php occ maintenance:install --database "{{dbms}}" --database-name "{{pac}}_{{user}}" --database-user "{{pac}}_{{user}}" --database-pass "{{password}}" --admin-user "admin_nextcloud" --admin-pass "{{random_password}}"
      touch ~/ansible.nextcloud_installed
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_nextcloud_installed"

  - name: set the trusted domain
    become: yes
    become_user: "{{pac}}-{{user}}"
    lineinfile:
      path: /home/pacs/{{pac}}/users/{{user}}/nextcloud/config/config.php
      regexp: "^.*0 => 'localhost',$"
      line: "    0 => 'localhost', 1 => '{{domain}}',"

  - name: install default apps
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      # see https://docs.nextcloud.com/server/19/admin_manual/configuration_server/occ_command.html#apps-commands-label
      php -d memory_limit=512M ./occ app:install {{item}}
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      creates: "/home/pacs/{{pac}}/users/{{user}}/nextcloud/apps/{{item}}"
    loop: "{{ ['richdocuments', 'richdocumentscode', 'contacts', 'calendar', 'mail', 'spreed', 'groupfolders', 'twofactor_totp'] }}"

  ##################################
  ## configuration
  ##################################

  - name: upload redis configuration
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/etc/redis.conf" src="templates/redis.conf" mode=0600

  - name: upload turnserver configuration
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/etc/turnserver.conf" src="templates/turnserver.conf" mode=0600

  - name: upload monit configuration
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/.monitrc" src="templates/monitrc" mode=0600

  - name: upload logrotate configuration
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/.logrotate" src="templates/logrotate" mode=0600

  ########################
  ## setup the apache site
  ########################
  - name: Check for htdocs-ssl directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    stat:
      path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
    register: htdocsssl
  - name: drop htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
       state: absent
    when: htdocsssl.stat.exists and htdocsssl.stat.isdir
  - name: create symbolic link for htdocs-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/nextcloud"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl"
      state: link
  - name: upload .htaccess file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template:
      src: "templates/htaccess"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/.htaccess"
  - name: upload php.ini file
    become: yes
    become_user: "{{pac}}-{{user}}"
    template:
      src: "templates/php.ini"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/fastcgi-ssl/php.ini"

  ####################################
  ## install cron jobs
  ####################################
  - name: start monit as cronjob
    become: yes
    become_user: "{{pac}}-{{user}}"
    cron:
      name: "start monit at reboot"
      special_time: reboot
      job: rm -f $HOME/var/run/monit.id && /usr/bin/monit -c "$HOME/.monitrc"
  - name: run logrotate once a day
    become: yes
    become_user: "{{pac}}-{{user}}"
    cron:
      name: "logrotate"
      minute: "27"
      hour: "1"
      job: "/usr/sbin/logrotate -s $HOME/.logrotate.state $HOME/.logrotate"
  - name: run nextcloud cronjob
    become: yes
    become_user: "{{pac}}-{{user}}"
    cron:
      name: "nextcloud"
      minute: "*/5"
      job: "/usr/bin/php $HOME/nextcloud/cron.php"
  - name: update all nextcloud apps each night
    become: yes
    become_user: "{{pac}}-{{user}}"
    cron:
      name: "nextcloud app updates"
      hour: "1"
      minute: "12"
      job: "/usr/bin/php $HOME/nextcloud/occ app:update --all -n --no-ansi"

  ##############################################
  ## start the redis and turn services via monit
  ##############################################
  - name: start monit
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      /usr/bin/monit -c ".monitrc"
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/"
      creates: "/home/pacs/{{pac}}/users/{{user}}/var/run/monit.id"
